export const leadershipData = [
    {
        name: "Spencer Douangphouxay",
        title: "Executive President",
        image: "/portraits/SpencerDouangphouxay.jpeg",
        pronouns: "He/Him",
    },
    {
        name: "Citlali Gonzalez",
        title: "Executive President",
        image: "/portraits/CitlaliGonzalez.jpg",
        pronouns: "She/They",
    },
    {
        name: "Sofia Cielak",
        title: "Exce Senior Advisor",
        image: "/portraits/SofiaCielak.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Chole Choi",
        title: "Entertainment Director",
        image: "/portraits/CholeChoi.jpg",
        pronouns: "She/Her",
    },
    {
        name: "Isaiah Rivera",
        title: "Entertainment Director",
        image: "/portraits/IsaiahRivera.png",
        pronouns: "He/Him",
    },
    {
        name: "Anjali Nayak",
        title: "Entertainment Assistant Director, DEI Assistant Director",
        image: "/portraits/AnjaliNayak.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Maggie Heaphy",
        title: "Sports Director",
        image: "/portraits/MaggieHeaphy.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Finn McHugh",
        title: "Assistant Sports Director",
        image: "/portraits/placeholder.png",
        pronouns: "He/Him",
    },
    {
        name: "Audrey Jacobson",
        title: "Entertainment Senior Advisor",
        image: "/portraits/AudreyJacobson.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Jack Curran",
        title: "Entertainment Senior Advisor",
        image: "/portraits/JackCurran.jpg",
        pronouns: "He/Him",
    },
    {
        name: "Shelby Green",
        title: "Entertainment Senior Advisor",
        image: "/portraits/ShelbyGreen.png",
        pronouns: "She/Her",
    },
    {
        name: "Tara Chakravorty",
        title: "Studios Senior Advisor",
        image: "/portraits/TaraChakravorty.jpg",
        pronouns: "She/Her",
    },
    {
        name: "Reagan Calaguas",
        title: "Studios Director of External Affairs",
        image: "/portraits/ReaganCalaguas.jpg",
        pronouns: "He/Him",
    },
    {
        name: "Ashley Perez",
        title: "Studios Director",
        image: "/portraits/AshleyPerez.jpg",
        pronouns: "She/Her",
    },
    {
        name: "Cristian Rojas",
        title: "Studios Director",
        image: "/portraits/CristianRojas.png",
        pronouns: "He/Him",
    },
    {
        name: "Leslie Juarez",
        title: "Studios Director",
        image: "/portraits/LeslieJuarez.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Star Avila",
        title: "News Senior Advisor",
        image: "/portraits/StarAvila.jpeg",
        pronouns: "They/Them",
    },
    {
        name: "Isabella Liu",
        title: "News Director",
        image: "/portraits/IsabellaLiu.jpg",
        pronouns: "She/Her",
    },
    {
        name: "Krishna Sam",
        title: "News Director",
        image: "/portraits/KrishnaSam.jpg",
        pronouns: "He/Him",
    },
    {
        name: "Tarini Kakkar",
        title: "News Assistant Director",
        image: "/portraits/TariniKakkar.jpg",
        pronouns: "She/Her",
    },
    {
        name: "Alexis Rico",
        title: "News Assistant Director, DEI Director",
        image: "/portraits/AlexisRico.jpeg",
        pronouns: "He/Him",
    },
    {
        name: "Lily Grodzins",
        title: "DEI Assistant Director",
        image: "/portraits/LilyGrodzins.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Nicole Aros",
        title: "Oskis Director",
        image: "/portraits/NicoleAros.jpg",
        pronouns: "She/Her",
    },
    {
        name: "Nethumi Kannangara",
        title: "Marketing Director",
        image: "/portraits/NethumiKannangara.jpeg",
        pronouns: "She/Her",
    },
    {
        name: "Nathan Son",
        title: "Marketing Director",
        image: "/portraits/NathanSon.jpeg",
        pronouns: "He/Him",
    },
    {
        name: "Evangeline Lim",
        title: "Marketing Assistant Director",
        image: "/portraits/placeholder.png",
        pronouns: "She/Her",
    },
    {
        name: "Abigail Townsend",
        title: "Marketing Assistant Director",
        image: "/portraits/AbigailTownsend.jpg",
        pronouns: "She/Her",
    },
];